[package]
name = "authenc-models"
version.workspace = true
edition.workspace = true
description = "Domain models for Authenc IAM"
license.workspace = true
repository.workspace = true

[dependencies]
authenc-core = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tokio-postgres = { workspace = true }
