pub mod audit;
pub use audit::{add_audit_log, get_audit_logs, create_audit_routes};
pub mod permission_check;
pub use permission_check::{check_user_permission, create_permission_check_routes};
pub mod user_permission;
pub use user_permission::get_user_permissions;
// API endpoints (REST/gRPC) will be implemented here
pub mod auth;
pub use auth::{login, create_auth_routes};
pub mod user;
pub use user::{create_user_routes};
pub mod auth_bearer;
pub mod realm;
pub use realm::{create_realm_routes};
pub mod role;
pub use role::{create_role_routes};
pub mod user_role;
pub use user_role::{assign_role, unassign_role, create_user_role_routes};
pub mod permission;
pub use permission::{create_permission_routes};
