use crate::error::AuthencError;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Realm entity representing a tenant or namespace with enterprise features
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Realm {
    /// Unique identifier for the realm
    pub id: Uuid,
    /// Name of the realm (must be unique)
    pub name: String,
    /// Display name for the realm
    pub display_name: Option<String>,
    /// Description of the realm
    pub description: Option<String>,
    /// Whether the realm is enabled
    pub enabled: bool,
    /// SSL requirement level ("external", "none", "all")
    pub ssl_required: String,
    /// Whether user registration is allowed
    pub registration_allowed: bool,
    /// Whether email can be used as username during registration
    pub registration_email_as_username: bool,
    /// Whether "remember me" functionality is enabled
    pub remember_me: bool,
    /// Whether email verification is required
    pub verify_email: bool,
    /// Whether login with email is allowed
    pub login_with_email_allowed: bool,
    /// Whether duplicate emails are allowed across users
    pub duplicate_emails_allowed: bool,
    /// Whether password reset is allowed
    pub reset_password_allowed: bool,
    /// Whether users can edit their username
    pub edit_username_allowed: bool,
    /// Whether brute force protection is enabled
    pub brute_force_protected: bool,
    /// Maximum time to wait after failed login attempts (seconds)
    pub max_failure_wait_seconds: i32,
    /// Minimum time to wait between quick login attempts (seconds)
    pub minimum_quick_login_wait_seconds: i32,
    /// Time increment for wait after failed attempts (seconds)
    pub wait_increment_seconds: i32,
    /// Quick login check interval (milliseconds)
    pub quick_login_check_milli_seconds: i64,
    /// Maximum delta time for login attempts (seconds)
    pub max_delta_time_seconds: i32,
    /// Failure factor for brute force detection
    pub failure_factor: i32,
    /// Default signature algorithm for tokens
    pub default_signature_algorithm: String,
    /// Whether refresh tokens should be revoked
    pub revoke_refresh_token: bool,
    /// Maximum number of times a refresh token can be reused
    pub refresh_token_max_reuse: i32,
    /// Lifespan of access tokens (seconds)
    pub access_token_lifespan: i32,
    /// Lifespan of access tokens for implicit flow (seconds)
    pub access_token_lifespan_for_implicit_flow: i32,
    /// SSO session idle timeout (seconds)
    pub sso_session_idle_timeout: i32,
    /// SSO session maximum lifespan (seconds)
    pub sso_session_max_lifespan: i32,
    /// SSO session idle timeout when remember me is used (seconds)
    pub sso_session_idle_timeout_remember_me: i32,
    /// SSO session maximum lifespan when remember me is used (seconds)
    pub sso_session_max_lifespan_remember_me: i32,
    /// Offline session idle timeout (seconds)
    pub offline_session_idle_timeout: i32,
    /// Offline session maximum lifespan (seconds)
    pub offline_session_max_lifespan: i32,
    /// Client session idle timeout (seconds)
    pub client_session_idle_timeout: i32,
    /// Client session maximum lifespan (seconds)
    pub client_session_max_lifespan: i32,
    /// Access code lifespan (seconds)
    pub access_code_lifespan: i32,
    /// Access code lifespan for user actions (seconds)
    pub access_code_lifespan_user_action: i32,
    /// Access code lifespan for login (seconds)
    pub access_code_lifespan_login: i32,
    /// Action token lifespan when generated by admin (seconds)
    pub action_token_generated_by_admin_lifespan: i32,
    /// Action token lifespan when generated by user (seconds)
    pub action_token_generated_by_user_lifespan: i32,
    /// OAuth2 device code lifespan (seconds)
    pub oauth2_device_code_lifespan: i32,
    /// OAuth2 device polling interval (seconds)
    pub oauth2_device_polling_interval: i32,
    /// Additional realm attributes as JSON
    pub attributes: Option<serde_json::Value>,
    /// Timestamp when the realm was created
    pub created_at: DateTime<Utc>,
    /// Timestamp when the realm was last updated
    pub updated_at: DateTime<Utc>,
    /// Timestamp when the realm was soft deleted
    pub deleted_at: Option<DateTime<Utc>>,
}

/// Realm creation request
#[derive(Debug, Clone, Deserialize)]
pub struct CreateRealmRequest {
    /// Name of the realm (must be unique)
    pub name: String,
    /// Display name for the realm
    pub display_name: Option<String>,
    /// Description of the realm
    pub description: Option<String>,
    /// Whether the realm is enabled
    pub enabled: Option<bool>,
    /// Additional realm attributes as JSON
    pub attributes: Option<serde_json::Value>,
}

/// Realm update request
#[derive(Debug, Deserialize)]
pub struct UpdateRealmRequest {
    /// New display name for the realm
    pub display_name: Option<String>,
    /// New description for the realm
    pub description: Option<String>,
    /// Whether the realm should be enabled
    pub enabled: Option<bool>,
    /// SSL requirement level ("external", "none", "all")
    pub ssl_required: Option<String>,
    /// Whether user registration is allowed
    pub registration_allowed: Option<bool>,
    /// Whether email verification is required
    pub verify_email: Option<bool>,
    /// Whether password reset is allowed
    pub reset_password_allowed: Option<bool>,
    /// Whether brute force protection is enabled
    pub brute_force_protected: Option<bool>,
    /// Additional realm attributes as JSON
    pub attributes: Option<serde_json::Value>,
}

/// Realm response
#[derive(Debug, Serialize)]
pub struct RealmResponse {
    /// Unique identifier for the realm
    pub id: Uuid,
    /// Name of the realm
    pub name: String,
    /// Display name of the realm
    pub display_name: Option<String>,
    /// Description of the realm
    pub description: Option<String>,
    /// Whether the realm is enabled
    pub enabled: bool,
    /// Timestamp when the realm was created
    pub created_at: DateTime<Utc>,
    /// Timestamp when the realm was last updated
    pub updated_at: DateTime<Utc>,
}

impl From<Realm> for RealmResponse {
    fn from(realm: Realm) -> Self {
        Self {
            id: realm.id,
            name: realm.name,
            display_name: realm.display_name,
            description: realm.description,
            enabled: realm.enabled,
            created_at: realm.created_at,
            updated_at: realm.updated_at,
        }
    }
}

impl Default for Realm {
    fn default() -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            name: "master".to_string(),
            display_name: Some("Master".to_string()),
            description: Some("Master realm".to_string()),
            enabled: true,
            ssl_required: "external".to_string(),
            registration_allowed: false,
            registration_email_as_username: false,
            remember_me: true,
            verify_email: false,
            login_with_email_allowed: true,
            duplicate_emails_allowed: false,
            reset_password_allowed: true,
            edit_username_allowed: false,
            brute_force_protected: true,
            max_failure_wait_seconds: 900,
            minimum_quick_login_wait_seconds: 60,
            wait_increment_seconds: 60,
            quick_login_check_milli_seconds: 1000,
            max_delta_time_seconds: 60 * 60 * 12, // 12 hours
            failure_factor: 30,
            default_signature_algorithm: "RS256".to_string(),
            revoke_refresh_token: false,
            refresh_token_max_reuse: 0,
            access_token_lifespan: 300,                   // 5 minutes
            access_token_lifespan_for_implicit_flow: 900, // 15 minutes
            sso_session_idle_timeout: 1800,               // 30 minutes
            sso_session_max_lifespan: 36000,              // 10 hours
            sso_session_idle_timeout_remember_me: 0,
            sso_session_max_lifespan_remember_me: 0,
            offline_session_idle_timeout: 2592000, // 30 days
            offline_session_max_lifespan: 5184000, // 60 days
            client_session_idle_timeout: 0,
            client_session_max_lifespan: 0,
            access_code_lifespan: 60,                        // 1 minute
            access_code_lifespan_user_action: 300,           // 5 minutes
            access_code_lifespan_login: 1800,                // 30 minutes
            action_token_generated_by_admin_lifespan: 43200, // 12 hours
            action_token_generated_by_user_lifespan: 300,    // 5 minutes
            oauth2_device_code_lifespan: 600,                // 10 minutes
            oauth2_device_polling_interval: 5,
            attributes: None,
            created_at: now,
            updated_at: now,
            deleted_at: None,
        }
    }
}

impl Realm {
    /// Create a new realm with default values
    pub fn new(name: String) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: name.clone(),
            display_name: Some(name),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            ..Default::default()
        }
    }

    /// Update realm fields
    pub fn update(&mut self, request: UpdateRealmRequest) {
        if let Some(display_name) = request.display_name {
            self.display_name = Some(display_name);
        }
        if let Some(description) = request.description {
            self.description = Some(description);
        }
        if let Some(enabled) = request.enabled {
            self.enabled = enabled;
        }
        if let Some(ssl_required) = request.ssl_required {
            self.ssl_required = ssl_required;
        }
        if let Some(registration_allowed) = request.registration_allowed {
            self.registration_allowed = registration_allowed;
        }
        if let Some(verify_email) = request.verify_email {
            self.verify_email = verify_email;
        }
        if let Some(reset_password_allowed) = request.reset_password_allowed {
            self.reset_password_allowed = reset_password_allowed;
        }
        if let Some(brute_force_protected) = request.brute_force_protected {
            self.brute_force_protected = brute_force_protected;
        }
        if let Some(attributes) = request.attributes {
            self.attributes = Some(attributes);
        }
        self.updated_at = Utc::now();
    }

    /// Check if realm is active
    pub fn is_active(&self) -> bool {
        self.enabled && self.deleted_at.is_none()
    }

    /// Soft delete the realm
    pub fn delete(&mut self) {
        self.deleted_at = Some(Utc::now());
        self.updated_at = Utc::now();
    }

    /// Get realm attribute
    pub fn get_attribute(&self, key: &str) -> Option<&serde_json::Value> {
        self.attributes.as_ref()?.get(key)
    }

    /// Set realm attribute
    pub fn set_attribute(&mut self, key: String, value: serde_json::Value) {
        let mut attributes = self
            .attributes
            .clone()
            .unwrap_or_else(|| serde_json::json!({}));
        if let serde_json::Value::Object(ref mut map) = attributes {
            map.insert(key, value);
        }
        self.attributes = Some(attributes);
        self.updated_at = Utc::now();
    }

    /// Remove realm attribute
    pub fn remove_attribute(&mut self, key: &str) {
        if let Some(serde_json::Value::Object(ref mut map)) = self.attributes {
            map.remove(key);
        }
        self.updated_at = Utc::now();
    }
}

