pub mod audit;
pub use audit::{add_audit_log, get_audit_logs};
pub mod permission_check;
pub use permission_check::check_user_permission;
pub mod user_permission;
pub use user_permission::get_user_permissions;
// API endpoints (REST/gRPC) will be implemented here
pub mod auth;
pub mod user;
pub mod auth_bearer;
pub use user::{get_users, create_user, get_user_by_id, update_user, delete_user, update_password};
pub mod realm;
pub use realm::{get_realms, get_realm_by_name, create_realm, delete_realm};
pub mod role;
pub use role::{get_roles, create_role, delete_role};
pub use role::{assign_permission_to_role, unassign_permission_from_role};
pub mod user_role;
pub use user_role::{assign_role, unassign_role};
pub mod permission;
pub use permission::{get_permissions, create_permission, delete_permission};
